const express=require('express');
const crypto=require('crypto');
const {readJson,updateJson}=require('../utils/store');
const {requireAuth,requireRole}=require('../middleware/auth');
const {calculateRisk}=require('../services/risk');
const {text,mobile,oneOf,number,bool,coordinates,ValidationError,DISASTER_TYPES,SEVERITIES,INCIDENT_STATUSES,TEAM_STATUSES,SOS_STATUSES}=require('../utils/validation');
const router=express.Router();
router.use(requireAuth);
const operator=requireRole('operator','admin');
const now=()=>new Date().toISOString();
const id=prefix=>`${prefix}-${crypto.randomUUID()}`;
const severityRank=Object.fromEntries(SEVERITIES.map((s,i)=>[s,i]));
const DEFAULT_SETTINGS={theme:'dark',alertSeverity:'Moderate',rememberLocation:false,notifications:true,reducedMotion:false,highContrast:false,compactDashboard:false,sound:false};
const INCIDENT_TRANSITIONS={
  Reported:['Reported','Verified'],
  Verified:['Reported','Verified','Team Assigned'],
  'Team Assigned':['Verified','Team Assigned','Responding'],
  Responding:['Team Assigned','Responding','Resolved'],
  Resolved:['Resolved']
};
const SOS_TRANSITIONS={
  Sent:['Sent','Received'],
  Received:['Received','Team Assigned','Resolved'],
  'Team Assigned':['Received','Team Assigned','Responding','Resolved'],
  Responding:['Team Assigned','Responding','Resolved'],
  Resolved:['Resolved']
};

function haversine(a,b){const R=6371,toRad=d=>d*Math.PI/180;const dLat=toRad(b.latitude-a.latitude),dLon=toRad(b.longitude-a.longitude);const x=Math.sin(dLat/2)**2+Math.cos(toRad(a.latitude))*Math.cos(toRad(b.latitude))*Math.sin(dLon/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}
function queryCoords(req){if(req.query.lat===undefined||req.query.lon===undefined)return null;return {latitude:number(req.query.lat,{min:-90,max:90,field:'Latitude'}),longitude:number(req.query.lon,{min:-180,max:180,field:'Longitude'})};}
function normalizeState(raw={}){return {alerts:raw.alerts||{},notifications:raw.notifications||{},settings:{...DEFAULT_SETTINGS,...(raw.settings||{})}};}
function userState(userId){const all=readJson('user_state.json',{});return normalizeState(all[userId]);}
function patchUserState(userId,mutator){let result;updateJson('user_state.json',{},all=>{const current=normalizeState(all[userId]);result=normalizeState(mutator(structuredClone(current))||current);return {...all,[userId]:result};});return result;}
function publicAlert(a,state){const s=state.alerts?.[a.id]||{};return {...a,read:!!s.read,pinned:!!s.pinned,dismissed:!!s.dismissed};}
function sheltersWithDistance(coords){return readJson('shelters.json',[]).map(s=>({...s,distanceKm:coords?Number(haversine(coords,{latitude:s.latitude,longitude:s.longitude}).toFixed(1)):null})).sort((a,b)=>coords?(a.distanceKm-b.distanceKm):(b.available-a.available));}
function appendNotification(notification){updateJson('notifications.json',[],items=>[{id:id('NOT'),timestamp:now(),...notification},...items].slice(0,250));}
function visibleNotification(n,user){const roleOk=!n.targetRole||n.targetRole===user.role||(n.targetRole==='operator'&&user.role==='admin');return (!n.targetUserId||n.targetUserId===user.id)&&roleOk;}
function requirePatch(body,keys){if(!body||!keys.some(k=>Object.prototype.hasOwnProperty.call(body,k)))throw new ValidationError(`Provide at least one of: ${keys.join(', ')}.`);}
function validTransition(current,next,map,field='Status'){if(!map[current]?.includes(next))throw new ValidationError(`${field} cannot move directly from ${current} to ${next}.`);return next;}
function findAssignableTeam(teams,teamId,{incidentId=null,sosId=null}={}){const team=teams.find(t=>t.id===teamId);if(!team)throw new ValidationError('Selected response team does not exist.');if(team.status==='Offline')throw new ValidationError('Offline response teams cannot be assigned.');if(team.assignedIncidentId&&team.assignedIncidentId!==incidentId)throw new ValidationError('Selected team is already assigned to another incident.');if(team.assignedSosId&&team.assignedSosId!==sosId)throw new ValidationError('Selected team is already assigned to an SOS report.');const assignedHere=(incidentId&&team.assignedIncidentId===incidentId)||(sosId&&team.assignedSosId===sosId);if(!assignedHere&&team.status!=='Available')throw new ValidationError('Selected response team is not currently available.');return team;}

router.get('/dashboard',(req,res)=>{const alerts=readJson('alerts.json',[]),incidents=readJson('incidents.json',[]),teams=readJson('teams.json',[]),disasters=readJson('disasters.json',[]);const coords=queryCoords(req);const shelters=sheltersWithDistance(coords),state=userState(req.user.id),minRank=severityRank[state.settings.alertSeverity]??0;const visibleAlerts=alerts.map(a=>publicAlert(a,state)).filter(a=>!a.dismissed&&(severityRank[a.severity]??0)>=minRank);const risks=disasters.map(d=>Number(d.risk)).filter(Number.isFinite).sort((a,b)=>b-a);const regionalRisk=risks.length?Math.round(risks.slice(0,Math.min(5,risks.length)).reduce((a,b)=>a+b,0)/Math.min(5,risks.length)):0;res.json({regionalRisk,alerts:visibleAlerts.length,criticalWarnings:visibleAlerts.filter(a=>['Severe','Critical'].includes(a.severity)).length,nearbyShelters:coords?shelters.filter(s=>s.distanceKm<=50&&s.status!=='Closed').length:null,availableTeams:teams.filter(t=>t.status==='Available'&&!t.assignedIncidentId&&!t.assignedSosId).length,activeIncidents:incidents.filter(i=>i.status!=='Resolved').length,alertsFeed:visibleAlerts.slice(0,5),incidents:incidents.slice(0,5),lastUpdated:now()});});
router.get('/alerts',(req,res)=>{const state=userState(req.user.id);res.json(readJson('alerts.json',[]).map(a=>publicAlert(a,state)));});
router.get('/alerts/:id',(req,res)=>{const a=readJson('alerts.json',[]).find(x=>x.id===req.params.id);if(!a)return res.status(404).json({error:'Alert not found.'});res.json(publicAlert(a,userState(req.user.id)));});
router.patch('/alerts/:id',(req,res)=>{if(!readJson('alerts.json',[]).some(x=>x.id===req.params.id))return res.status(404).json({error:'Alert not found.'});requirePatch(req.body,['read','pinned','dismissed']);const allowed={};for(const k of ['read','pinned','dismissed'])if(k in req.body)allowed[k]=bool(req.body[k],k);const state=patchUserState(req.user.id,s=>{s.alerts[req.params.id]={...(s.alerts[req.params.id]||{}),...allowed};return s;});res.json({id:req.params.id,...state.alerts[req.params.id]});});
router.post('/alerts/mark-all-read',(req,res)=>{const alerts=readJson('alerts.json',[]);patchUserState(req.user.id,s=>{alerts.forEach(a=>s.alerts[a.id]={...(s.alerts[a.id]||{}),read:true});return s;});res.json({message:'All alerts marked as read.'});});
router.get('/disasters',(req,res)=>res.json(readJson('disasters.json',[])));
router.get('/disasters/:id',(req,res)=>{const item=readJson('disasters.json',[]).find(x=>x.id===req.params.id);item?res.json(item):res.status(404).json({error:'Disaster event not found.'});});
router.get('/resources',(req,res)=>res.json(readJson('resources.json',[])));
router.get('/shelters',(req,res)=>res.json(sheltersWithDistance(queryCoords(req))));
router.get('/shelters/nearby',(req,res)=>{const coords=queryCoords(req);if(!coords)throw new ValidationError('Latitude and longitude are required.');const radius=number(req.query.radius??50,{min:1,max:500,field:'Radius'});res.json(sheltersWithDistance(coords).filter(s=>s.distanceKm<=radius));});

router.get('/teams',(req,res)=>res.json(readJson('teams.json',[])));
router.patch('/teams/:id',operator,(req,res)=>{requirePatch(req.body,['status']);const requested=oneOf(req.body.status,TEAM_STATUSES,'Team status');let updated;updateJson('teams.json',[],teams=>teams.map(t=>{if(t.id!==req.params.id)return t;if(t.assignedIncidentId||t.assignedSosId){if(requested!==t.status){const e=new ValidationError('Assigned team status is controlled from the linked incident or SOS workflow.');e.status=409;throw e;}updated=t;return t;}if(!['Available','Offline'].includes(requested))throw new ValidationError('Unassigned teams can only be set to Available or Offline.');updated={...t,status:requested,assignedIncidentId:null,assignedSosId:null,updatedAt:now()};return updated;}));if(!updated)return res.status(404).json({error:'Response team not found.'});res.json(updated);});

router.get('/incidents',(req,res)=>res.json(readJson('incidents.json',[])));
router.post('/incidents',operator,(req,res)=>{const item={id:id('INC'),title:text(req.body?.title,{min:3,max:100,field:'Incident title'}),type:oneOf(req.body?.type,DISASTER_TYPES,'Incident type'),severity:oneOf(req.body?.severity,SEVERITIES.filter(x=>x!=='Safe'),'Severity'),status:'Reported',teamId:null,team:'Unassigned',location:text(req.body?.location||'Unspecified',{min:2,max:120,field:'Location'}),createdBy:req.user.id,createdAt:now(),updatedAt:now()};updateJson('incidents.json',[],items=>[item,...items].slice(0,500));res.status(201).json(item);});
router.patch('/incidents/:id',operator,(req,res)=>{const body=req.body||{};requirePatch(body,['status','severity','title','teamId']);const teams=readJson('teams.json',[]);let updated,oldTeamId=null,newTeamId=null,releasedTeamId=null;updateJson('incidents.json',[],items=>items.map(item=>{if(item.id!==req.params.id)return item;oldTeamId=item.teamId||null;const next={...item};if(item.status==='Resolved'&&'teamId'in body)throw new ValidationError('Resolved incidents cannot be assigned to response teams.');if('severity'in body)next.severity=oneOf(body.severity,SEVERITIES.filter(x=>x!=='Safe'),'Severity');if('title'in body)next.title=text(body.title,{min:3,max:100,field:'Incident title'});
  if('teamId'in body){if(body.teamId===null||body.teamId===''){if(next.status==='Responding')throw new ValidationError('A responding incident must keep an assigned team.');releasedTeamId=next.teamId||null;next.teamId=null;next.team='Unassigned';if(next.status==='Team Assigned')next.status='Verified';}else{if(next.status==='Reported')throw new ValidationError('Verify the incident before assigning a response team.');const team=findAssignableTeam(teams,body.teamId,{incidentId:item.id});releasedTeamId=next.teamId&&next.teamId!==team.id?next.teamId:null;next.teamId=team.id;next.team=team.name;newTeamId=team.id;if(next.status==='Verified')next.status='Team Assigned';}}
  if('status'in body){const desired=oneOf(body.status,INCIDENT_STATUSES,'Incident status');validTransition(next.status,desired,INCIDENT_TRANSITIONS,'Incident status');if(['Team Assigned','Responding'].includes(desired)&&!next.teamId)throw new ValidationError(`${desired} requires an assigned response team.`);if(desired==='Resolved'){releasedTeamId=next.teamId||releasedTeamId;next.resolvedByTeam=next.team||next.resolvedByTeam||'Unassigned';next.teamId=null;next.team='Unassigned';}next.status=desired;}
  next.updatedAt=now();updated=next;return next;}));if(!updated)return res.status(404).json({error:'Incident not found.'});
  updateJson('teams.json',[],list=>list.map(t=>{if(releasedTeamId&&t.id===releasedTeamId)return {...t,status:'Available',assignedIncidentId:null,updatedAt:now()};if(updated.teamId&&t.id===updated.teamId)return {...t,status:updated.status==='Responding'?'Responding':'Assigned',assignedIncidentId:updated.id,assignedSosId:null,updatedAt:now()};if(oldTeamId&&oldTeamId!==updated.teamId&&t.id===oldTeamId)return {...t,status:'Available',assignedIncidentId:null,updatedAt:now()};return t;}));
  if(newTeamId)appendNotification({title:'Response team assigned',message:`${updated.team} assigned to ${updated.title}.`,type:'Team',severity:updated.severity,targetRole:'operator'});res.json(updated);
});

router.post('/risk',(req,res)=>res.json(calculateRisk(req.body)));

router.get('/tasks',(req,res)=>res.json(readJson('tasks.json',{})[req.user.id]||[]));
router.post('/tasks',(req,res)=>{const item={id:id('TASK'),title:text(req.body?.title,{min:2,max:120,field:'Task title'}),completed:false,createdAt:now(),updatedAt:now()};updateJson('tasks.json',{},all=>({...all,[req.user.id]:[item,...(all[req.user.id]||[])].slice(0,200)}));res.status(201).json(item);});
router.patch('/tasks/:id',(req,res)=>{requirePatch(req.body,['title','completed']);let updated;updateJson('tasks.json',{},all=>{const list=(all[req.user.id]||[]).map(t=>{if(t.id!==req.params.id)return t;const next={...t};if('title'in req.body)next.title=text(req.body.title,{min:2,max:120,field:'Task title'});if('completed'in req.body)next.completed=bool(req.body.completed,'Completed');next.updatedAt=now();updated=next;return next;});return {...all,[req.user.id]:list};});if(!updated)return res.status(404).json({error:'Task not found.'});res.json(updated);});
router.delete('/tasks/:id',(req,res)=>{let removed=false;updateJson('tasks.json',{},all=>{const before=all[req.user.id]||[],after=before.filter(t=>t.id!==req.params.id);removed=after.length!==before.length;return {...all,[req.user.id]:after};});if(!removed)return res.status(404).json({error:'Task not found.'});res.json({message:'Task removed.'});});

router.get('/sos',(req,res)=>{const all=readJson('sos.json',[]);res.json(['operator','admin'].includes(req.user.role)?all:all.filter(x=>x.userId===req.user.id));});
router.post('/sos',(req,res)=>{const emergencyType=oneOf(req.body?.emergencyType,['Medical','Fire','Flood','Earthquake','Threat','Other'],'Emergency type');const contactNumber=mobile(req.body?.contactNumber,'Contact number');const description=text(req.body?.description||'Emergency assistance requested',{min:3,max:500,field:'Description'});const rawLoc=req.body?.location||{};const coords=coordinates(rawLoc.coordinates||rawLoc,{required:false});const label=text(rawLoc.label||'Manual/unknown location',{min:2,max:160,field:'Location label'});const item={id:id('SOS'),userId:req.user.id,userName:req.user.fullName,emergencyType,contactNumber,description,location:{label,coordinates:coords},teamId:null,team:'Unassigned',createdAt:now(),updatedAt:now(),status:'Sent',simulated:true};updateJson('sos.json',[],items=>[item,...items].slice(0,500));appendNotification({title:'SOS received',message:`Simulated SOS ${item.id} was received by the Aegis demo command center.`,type:'SOS',severity:'Critical',targetUserId:req.user.id});appendNotification({title:'New simulated SOS',message:`${item.emergencyType} SOS from ${item.userName}.`,type:'SOS',severity:'Critical',targetRole:'operator'});res.status(201).json({message:'Simulated SOS received by the Aegis academic command center. This does not contact real emergency services.',event:item});});
router.patch('/sos/:id',operator,(req,res)=>{const body=req.body||{};requirePatch(body,['status','teamId']);const teams=readJson('teams.json',[]);let updated,oldTeamId=null,releasedTeamId=null,newTeamId=null;updateJson('sos.json',[],items=>items.map(item=>{if(item.id!==req.params.id)return item;oldTeamId=item.teamId||null;const next={...item};if(item.status==='Resolved'&&'teamId'in body)throw new ValidationError('Resolved SOS reports cannot be assigned to response teams.');if('teamId'in body){if(body.teamId===null||body.teamId===''){if(next.status==='Responding')throw new ValidationError('A responding SOS must keep an assigned team.');releasedTeamId=next.teamId||null;next.teamId=null;next.team='Unassigned';if(next.status==='Team Assigned')next.status='Received';}else{if(next.status==='Sent')throw new ValidationError('The SOS must be received before assigning a response team.');const team=findAssignableTeam(teams,body.teamId,{sosId:item.id});releasedTeamId=next.teamId&&next.teamId!==team.id?next.teamId:null;next.teamId=team.id;next.team=team.name;newTeamId=team.id;if(next.status==='Received')next.status='Team Assigned';}}
  if('status'in body){const desired=oneOf(body.status,SOS_STATUSES,'SOS status');validTransition(next.status,desired,SOS_TRANSITIONS,'SOS status');if(['Team Assigned','Responding'].includes(desired)&&!next.teamId)throw new ValidationError(`${desired} requires an assigned response team.`);if(desired==='Resolved'){releasedTeamId=next.teamId||releasedTeamId;next.resolvedByTeam=next.team||next.resolvedByTeam||'Unassigned';next.teamId=null;next.team='Unassigned';}next.status=desired;}next.updatedAt=now();updated=next;return next;}));if(!updated)return res.status(404).json({error:'SOS report not found.'});updateJson('teams.json',[],list=>list.map(t=>{if(releasedTeamId&&t.id===releasedTeamId)return {...t,status:'Available',assignedSosId:null,updatedAt:now()};if(updated.teamId&&t.id===updated.teamId)return {...t,status:updated.status==='Responding'?'Responding':'Assigned',assignedSosId:updated.id,assignedIncidentId:null,updatedAt:now()};if(oldTeamId&&oldTeamId!==updated.teamId&&t.id===oldTeamId)return {...t,status:'Available',assignedSosId:null,updatedAt:now()};return t;}));if(newTeamId)appendNotification({title:'SOS team assigned',message:`${updated.team} assigned to ${updated.id}.`,type:'SOS',severity:'Critical',targetUserId:updated.userId});res.json(updated);});

router.get('/notifications',(req,res)=>{const state=userState(req.user.id),seen=state.notifications;const list=readJson('notifications.json',[]).filter(n=>visibleNotification(n,req.user)).filter(n=>!seen[n.id]?.deleted).map(n=>({...n,read:!!seen[n.id]?.read}));res.json(list);});
router.patch('/notifications/:id',(req,res)=>{requirePatch(req.body,['read']);const item=readJson('notifications.json',[]).find(n=>n.id===req.params.id&&visibleNotification(n,req.user));if(!item)return res.status(404).json({error:'Notification not found.'});const read=bool(req.body.read,'Read');patchUserState(req.user.id,s=>{s.notifications[req.params.id]={...(s.notifications[req.params.id]||{}),read};return s;});res.json({id:req.params.id,read});});
router.delete('/notifications/:id',(req,res)=>{const item=readJson('notifications.json',[]).find(n=>n.id===req.params.id&&visibleNotification(n,req.user));if(!item)return res.status(404).json({error:'Notification not found.'});patchUserState(req.user.id,s=>{s.notifications[req.params.id]={...(s.notifications[req.params.id]||{}),deleted:true};return s;});res.json({message:'Notification removed.'});});
router.post('/notifications/mark-all-read',(req,res)=>{const items=readJson('notifications.json',[]).filter(n=>visibleNotification(n,req.user));patchUserState(req.user.id,s=>{items.forEach(n=>s.notifications[n.id]={...(s.notifications[n.id]||{}),read:true});return s;});res.json({message:'All notifications marked as read.'});});

router.get('/settings',(req,res)=>res.json(userState(req.user.id).settings));
router.patch('/settings',(req,res)=>{const body=req.body||{};requirePatch(body,['theme','alertSeverity','rememberLocation','notifications','reducedMotion','highContrast','compactDashboard','sound']);const allowed={};if('theme'in body)allowed.theme=oneOf(body.theme,['dark','light','system'],'Theme');if('alertSeverity'in body)allowed.alertSeverity=oneOf(body.alertSeverity,SEVERITIES,'Alert severity');for(const k of ['rememberLocation','notifications','reducedMotion','highContrast','compactDashboard','sound'])if(k in body)allowed[k]=bool(body[k],k);const state=patchUserState(req.user.id,s=>{s.settings={...s.settings,...allowed};return s;});res.json(state.settings);});

router.get('/analytics',(req,res)=>{const incidents=readJson('incidents.json',[]),alerts=readJson('alerts.json',[]),shelters=readJson('shelters.json',[]),teams=readJson('teams.json',[]),tasks=readJson('tasks.json',{})[req.user.id]||[],disasters=readJson('disasters.json',[]);const count=(arr,key)=>arr.reduce((o,x)=>(o[x[key]]=(o[x[key]]||0)+1,o),{});res.json({riskByDisaster:Object.fromEntries(Object.entries(count(disasters,'type')).map(([k,v])=>[k,Math.round(disasters.filter(d=>d.type===k).reduce((s,d)=>s+d.risk,0)/v)])),incidentsOverTime:[3,5,4,7,6,8,incidents.filter(i=>i.status!=='Resolved').length],alertSeverity:count(alerts,'severity'),shelterOccupancy:Object.fromEntries(shelters.slice(0,8).map(s=>[s.name,Math.round(s.occupied/s.capacity*100)])),teamAvailability:count(teams,'status'),preparednessCompletion:tasks.length?Math.round(tasks.filter(t=>t.completed).length/tasks.length*100):0,lastUpdated:now()});});
module.exports=router;
