const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const dataNames=['users.json','tasks.json','user_state.json','sos.json','incidents.json','teams.json','notifications.json'];
const backups=Object.fromEntries(dataNames.map(n=>[n,fs.readFileSync(path.join(root,'data',n),'utf8')]));
process.env.NODE_ENV='test';
process.env.PORT='31477';
process.env.JWT_SECRET='integration-test-secret-that-is-longer-than-thirty-two-characters';
process.env.SEED_DEMO_USER='true';
process.env.DEMO_PASSWORD='Demo@123';
process.env.TRUST_PROXY='false';
const {startServer}=require('../server/index');
let server,base='http://127.0.0.1:31477';
function cookieFrom(res){return (res.headers.get('set-cookie')||'').split(';')[0];}
async function json(url,options={}){const res=await fetch(base+url,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const body=await res.json().catch(()=>({}));return {res,body};}
async function login(email,password){const {res,body}=await json('/api/auth/login',{method:'POST',body:JSON.stringify({email,password})});assert.equal(res.status,200,JSON.stringify(body));return cookieFrom(res);}
test.before(async()=>{server=await startServer(31477);});
test.after(async()=>{await new Promise(r=>server.close(r));for(const [n,v] of Object.entries(backups))fs.writeFileSync(path.join(root,'data',n),v);});

test('health, no-store and security headers',async()=>{const res=await fetch(base+'/health');assert.equal(res.status,200);assert.ok(res.headers.get('content-security-policy'));assert.equal(res.headers.get('x-content-type-options'),'nosniff');assert.equal(res.headers.get('x-frame-options'),'DENY');assert.equal(res.headers.get('x-powered-by'),null);const c=await login('demo@aegis.local','Demo@123');const me=await fetch(base+'/api/auth/me',{headers:{Cookie:c}});assert.match(me.headers.get('cache-control')||'',/no-store/);});
test('demo operator can authenticate',async()=>{const c=await login('demo@aegis.local','Demo@123');const {res,body}=await json('/api/auth/me',{headers:{Cookie:c}});assert.equal(res.status,200);assert.equal(body.role,'operator');});
test('risk engine rejects invalid numbers and returns finite valid scores',async()=>{const c=await login('demo@aegis.local','Demo@123');let r=await json('/api/risk',{method:'POST',headers:{Cookie:c},body:JSON.stringify({temperature:'abc',rainfall:10,windSpeed:10,humidity:20,seismicActivity:1,waterLevel:1,terrainRisk:1,historicalFrequency:1})});assert.equal(r.res.status,400);r=await json('/api/risk',{method:'POST',headers:{Cookie:c},body:JSON.stringify({temperature:36,rainfall:120,windSpeed:45,humidity:78,seismicActivity:1.2,waterLevel:3.5,terrainRisk:4,historicalFrequency:5})});assert.equal(r.res.status,200);assert.ok(Number.isFinite(r.body.score));assert.equal(r.body.simulated,true);});
test('incident inputs are whitelisted and unsafe direct transitions are rejected',async()=>{const c=await login('demo@aegis.local','Demo@123');let r=await json('/api/incidents',{method:'POST',headers:{Cookie:c},body:JSON.stringify({title:'Test incident',type:'<img src=x onerror=alert(1)>',severity:'High',location:'Test zone'})});assert.equal(r.res.status,400);r=await json('/api/incidents/INC-1001',{method:'PATCH',headers:{Cookie:c},body:JSON.stringify({status:'Resolved',id:'OTHER'})});assert.equal(r.res.status,400);});
test('incident workflow assigns and releases teams consistently',async()=>{const c=await login('demo@aegis.local','Demo@123');let r=await json('/api/incidents',{method:'POST',headers:{Cookie:c},body:JSON.stringify({title:'Workflow verification incident',type:'Flood',severity:'High',location:'Test zone'})});assert.equal(r.res.status,201,JSON.stringify(r.body));const incidentId=r.body.id;r=await json(`/api/incidents/${incidentId}`,{method:'PATCH',headers:{Cookie:c},body:JSON.stringify({status:'Verified'})});assert.equal(r.res.status,200);r=await json(`/api/incidents/${incidentId}`,{method:'PATCH',headers:{Cookie:c},body:JSON.stringify({teamId:'RT-101'})});assert.equal(r.res.status,200);assert.equal(r.body.status,'Team Assigned');r=await json(`/api/incidents/${incidentId}`,{method:'PATCH',headers:{Cookie:c},body:JSON.stringify({status:'Responding'})});assert.equal(r.res.status,200);r=await json(`/api/incidents/${incidentId}`,{method:'PATCH',headers:{Cookie:c},body:JSON.stringify({status:'Resolved'})});assert.equal(r.res.status,200);assert.equal(r.body.teamId,null);const teams=await json('/api/teams',{headers:{Cookie:c}});const team=teams.body.find(t=>t.id==='RT-101');assert.equal(team.status,'Available');assert.equal(team.assignedIncidentId,null);});

test('resolved incidents cannot be re-assigned to a team',async()=>{const c=await login('demo@aegis.local','Demo@123');const r=await json('/api/incidents/INC-1006',{method:'PATCH',headers:{Cookie:c},body:JSON.stringify({teamId:'RT-101'})});assert.equal(r.res.status,400);});
test('SOS follows Sent -> Received -> Team Assigned -> Responding -> Resolved and releases its team',async()=>{const c=await login('demo@aegis.local','Demo@123');let r=await json('/api/sos',{method:'POST',headers:{Cookie:c},body:JSON.stringify({emergencyType:'Medical',contactNumber:'9999999998',description:'Integration test assistance request',location:{label:'Test zone',coordinates:{latitude:23.02,longitude:72.57}}})});assert.equal(r.res.status,201,JSON.stringify(r.body));assert.equal(r.body.event.status,'Sent');const sosId=r.body.event.id;let early=await json(`/api/sos/${sosId}`,{method:'PATCH',headers:{Cookie:c},body:JSON.stringify({teamId:'RT-101'})});assert.equal(early.res.status,400);r=await json(`/api/sos/${sosId}`,{method:'PATCH',headers:{Cookie:c},body:JSON.stringify({status:'Received'})});assert.equal(r.res.status,200);r=await json(`/api/sos/${sosId}`,{method:'PATCH',headers:{Cookie:c},body:JSON.stringify({teamId:'RT-101'})});assert.equal(r.res.status,200);assert.equal(r.body.status,'Team Assigned');r=await json(`/api/sos/${sosId}`,{method:'PATCH',headers:{Cookie:c},body:JSON.stringify({status:'Responding'})});assert.equal(r.res.status,200);r=await json(`/api/sos/${sosId}`,{method:'PATCH',headers:{Cookie:c},body:JSON.stringify({status:'Resolved'})});assert.equal(r.res.status,200);assert.equal(r.body.teamId,null);const teams=await json('/api/teams',{headers:{Cookie:c}});const team=teams.body.find(t=>t.id==='RT-101');assert.equal(team.status,'Available');assert.equal(team.assignedSosId,null);});
test('citizen registration is restricted from operator incident writes',async()=>{const email=`citizen-${Date.now()}@example.test`;let r=await json('/api/auth/register',{method:'POST',body:JSON.stringify({fullName:'Test Citizen',rollNumber:`T-${Date.now()}`,mobile:'9999999998',email,address:'Test Address',city:'Ahmedabad',state:'Gujarat',password:'Citizen123',confirmPassword:'Citizen123',terms:true})});assert.equal(r.res.status,201,JSON.stringify(r.body));const c=await login(email,'Citizen123');r=await json('/api/incidents',{method:'POST',headers:{Cookie:c},body:JSON.stringify({title:'Unauthorized incident',type:'Flood',severity:'High',location:'Zone'})});assert.equal(r.res.status,403);r=await json('/api/tasks',{method:'POST',headers:{Cookie:c},body:JSON.stringify({title:'Pack water'})});assert.equal(r.res.status,201);const taskId=r.body.id;r=await json(`/api/tasks/${taskId}`,{method:'PATCH',headers:{Cookie:c},body:JSON.stringify({completed:true})});assert.equal(r.res.status,200);assert.equal(r.body.completed,true);r=await json(`/api/tasks/${taskId}`,{method:'DELETE',headers:{Cookie:c}});assert.equal(r.res.status,200);});
test('API rejects wrong content type on mutations with a body',async()=>{const c=await login('demo@aegis.local','Demo@123');const res=await fetch(base+'/api/risk',{method:'POST',headers:{Cookie:c,'Content-Type':'text/plain'},body:'not-json'});assert.equal(res.status,415);});
test('unknown API routes return JSON 404',async()=>{const c=await login('demo@aegis.local','Demo@123');const {res,body}=await json('/api/does-not-exist',{headers:{Cookie:c}});assert.equal(res.status,404);assert.equal(body.error,'API endpoint not found.');});
test('Neuro-Sync verifies distress text and a structural anomaly',async()=>{const c=await login('demo@aegis.local','Demo@123');const before=Array(64).fill(140),after=Array(64).fill(20);const {res,body}=await json('/api/neuro-sync/verify',{method:'POST',headers:{Cookie:c},body:JSON.stringify({message:'People trapped after collapse at 23.0225, 72.5714',before,after,threshold:.75})});assert.equal(res.status,200,JSON.stringify(body));assert.equal(body.nlp.coordinates.latitude,23.0225);assert.equal(body.anomaly,true);assert.equal(body.verifiedCritical,true);assert.ok(body.ssim<.75);});
test('Neuro-Sync capability endpoint requires authentication',async()=>{const unauthenticated=await json('/api/neuro-sync/capabilities');assert.equal(unauthenticated.res.status,401);const c=await login('demo@aegis.local','Demo@123');const authenticated=await json('/api/neuro-sync/capabilities',{headers:{Cookie:c}});assert.equal(authenticated.res.status,200);assert.equal(authenticated.body.stream.protocol,'WebSocket');});
